### ISSUE TITLE
`npm run build` command not work

### ISSUE THREAD

**Issue by maxim4ik93** [anovsiradj/yii2-theme-mazer#34]
![sss](https://github.com/anovsiradj/yii2-theme-mazer/assets/48281829/7b3f838e-3c74-4a3b-9a9e-94d9d7674612)
`npm run build` command not work

**Comment by anovsiradj** [comment]
https://github.com/zuramai/mazer/releases/tag/v2.1.0
they have done some refactoring which make some files gone missing.

i have released v2 to fix the build and update mazer to latest
